
server:
  enabled: true
  address: ":9091"
  timeout: 1m
  pprof: true

logger:
  level: "info"
  stdout: true

controller:
  layer4Metrics:
    enabled: true
    requiredLabels:
#      - "source.host"
#      - "source.port"
#      - "destination.host"
#      - "destination.port"

sniffer.ifaces: 'lo'
sniffer.engine: pcap
sniffer.ipv4Only: false
#sniffer.file: "/tmp/apm-worker.pcap"

sniffer.protocols:
  rules:
#    - name: "redis"
#      protocol: "redis"
#      ports: [6379]

#    - name: "http"
#      protocol: "http"
#      ports: [8083]

#    - name: "mysql"
#      protocol: "mysql"
#      ports: [3306]

    - name: "grpc"
      protocol: "grpc"
      ports: [8085]

#    - name: dns
#      protocol: "dns"
#      ports: [53]

#    - name: mongodb
#      protocol: "mongodb"
#      ports: [27017]

#    - name: "postgresql"
#      protocol: "postgresql"
#      ports: [5432]

#    - name: "kafka"
#      protocol: "kafka"
#      ports: [9092]

#    - name: amqp
#      protocol: "amqp"
#      ports: [5672]

processor:
  - name: roundtripstometrics
    config:
      http:
        requireLabels:
          - "server.host"
          - "server.port"
          - "request.method"
          - "request.path"
          - "response.status_code"

      redis:
        requireLabels:

      kafka:
        requireLabels:
          - request.api

      amqp:
        requireLabels:
          - "request.class"
          - "request.method"

  - name: roundtripstotraces
    config:

#  - name: roundtripsfilter
#    config:

pipeline:
#  - name: "traces/common"
#    processors:
#      - roundtripstotraces

  - name: "metrics/common"
    processors:
      - roundtripstometrics

metricsStorage:
  enabled: true
  expired: 5m
  vmHistogram: false

exporter:
  traces:
    enabled: false
    endpoint: http://172.16.22.128:4318/v1/traces
    batch: 10
    interval: 3s

  metrics:
    enabled: false
    endpoint: http://localhost:4318/prometheus/write
    interval: 1m

  roundtrips:
    enabled: false
    console: true
    filename: "roundtrips.log"
    maxSize: 100
    maxBackups: 10
    maxAge: 30
